---
title: "MB5370-Techniques in Marine Science 1: Module.01- Workshop 2"
subject: Introduction to Programming
output: html_document
date: "2026-05-21"
---
##Workshop.02- Visualization
#Introduction:
#Turning data into graphics with code is a great tool to help scientists explore the datasets to answer research questions. 

```{r warning=FALSE}
library("tidyverse")
```

```{r}
mpg
```
##2.17 Create a ggplot
```{r}
ggplot(data = mpg)+
  geom_point(mapping=aes(x=displ, y=hwy))
#shows a negative relationship between engine size(displ) and fuel efficiency(hwy). This can interpret the results of larger the engine size the lower the fuel efficiency due the unbalanced load of effort and energy input. 
```
#2.18 Understanding the 'grammar of graphics'
```{r}
ggplot(data = mpg)+
  geom_point(mapping=aes(x=displ, y=hwy, colour=class)) # color represents the type of vehicles in the dataset and it is shown how each vehicle has varying engine size and fuel efficiency. 
```

```{r warning=FALSE}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size = class)) # not the best aesthetic to represent data since some data points can be overlapped by other data points
```

```{r warning=FALSE}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class)) # this may also not be the best to represent the data since some data points are hard to see which can be great for interpretation on the relationship between fuel efficiency and engine size but not the best for visualization purposes. 
```

```{r warning=FALSE}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class)) # this can be a good way to visualize the data but the color by class is better visually, especially for those reading the paper with so scientific background, having a more simple layout of the data visualization can make science more accessible. 
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), color = "blue") # this does not represent the different class vehicle types, it only looks like a negative trend of only one vehicle. This graph aesthetics is not specific or appropriate enough for this kind of study. 
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), colour = "blue")+
  aes(colour = displ < 5)
```
## 2.19 Troubleshooting code
```{r}
ggplot(data = mpg) +
 geom_point(mapping = aes(x = displ, y = hwy))  #this code has been fixed. The previous version had a "+" in-front of "geom_point," but that is incorrect. The best way to add on new aesthetics is to place the "+" at the end of the top line of code. 
```

##2.20 Facet and Panel plots
```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, nrow = 2)
```

```{r}
# this combines two variables
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(drv ~ cyl)
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))+ 
facet_grid(. ~ cyl)
```
##2.21 Fitting Simple Lines
```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) 
```

```{r message=FALSE}
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy))
```

```{r warning=FALSE}
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy))
```

```{r}
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv)) # the lines represent the type of drive the cars are, ex: 4 is 4WD, f is FWD, and r is RWD. 
```

```{r}
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv))
```

```{r}
ggplot(data = mpg) +
  geom_smooth(
    mapping = aes(x = displ, y = hwy, color = drv),
    show.legend = FALSE,
  )
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes(x = displ, y = hwy))
```

```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) + 
  geom_smooth()
```

```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) + 
  geom_smooth(data = filter(mpg, class == "subcompact"), se = FALSE)
```
##Exercise: 
```{r message=FALSE}
#you can  use a histogram geom to help produce a line chart
# these two codes are essentially the same when producing visualization of data but the difference is: in the top code, it specifies the parameters of the data early on, then with the second code only specifies the aesthetics in both geom's which can be a bit harder and more time consuming.
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth()

ggplot() + 
  geom_point(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_smooth(data = mpg, mapping = aes(x = displ, y = hwy))
```
##2.22 Transformations and Stats
```{r}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut))
```

```{r}
ggplot(data = diamonds) + 
  stat_count(mapping = aes(x = cut)) # the graph above and the one this code produces are showing the same results but the code is different. Using geom_bar and stat_count can be used interchangeably. 
```
##2.22.2 Overriding defaults in ggplot2
```{r}
demo <- tribble(
  ~cut,         ~freq,
  "Fair",       1610,
  "Good",       4906,
  "Very Good",  12082,
  "Premium",    13791,
  "Ideal",      21551
)
demo

ggplot(data = demo) +
  geom_bar(mapping = aes(x = cut, y = freq), stat = "identity")

```

```{r warning=FALSE}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, y = stat(prop), group = 1))
```

```{r}
ggplot(data = diamonds) + 
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.min = min,
    fun.max = max,
    fun = median
  )
```

```{r}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, colour = cut))
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = cut))
```

```{r}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity))
```

```{r}
ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) + 
  geom_bar(alpha = 1/5, position = "identity")

#To color the bar outlines with no fill color
ggplot(data = diamonds, mapping = aes(x = cut, colour = clarity)) + 
  geom_bar(fill = NA, position = "identity")
```


```{r}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "fill") # this graph represents the quality cut diamonds better than the previous graphs. This shows the degree the cut will be based on the clarity of the diamond
```

```{r}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "dodge")
```

